# NOTE Mage is the class, Conjuror, Magician, Sorcerer, Wizard, (Archmage) are the disiplines.
[[classes]]
  name="warrior"
  code="WA"
  [[classes.histogram]]
    attribute="strength"
	  weight=25.0
  [[classes.histogram]]
    attribute="dexterity"
    weight=12.5
  [[classes.histogram]]
    attribute="intelligence"
    weight=12.5
  [[classes.histogram]]
    attribute="constitution"
    weight=50.0
    
[[classes]]
  name="paladin"
  code="PA"
  [[classes.histogram]]
    attribute="strength"
    weight=20.0
      [[classes.histogram]]
    attribute="dexterity"
    weight=17.5
  [[classes.histogram]]
    attribute="intelligence"
    weight=22.5
  [[classes.histogram]]
    attribute="constitution"
    weight=40.0
    
[[classes]]
  name="bard"
  code="BA"
  [[classes.histogram]]
    attribute="strength"
    weight=15.0
  [[classes.histogram]]
    attribute="dexterity"
    weight=25.0
  [[classes.histogram]]
    attribute="intelligence"
    weight=25.0
  [[classes.histogram]]
    attribute="constitution"
    weight=35.0
    
[[classes]]
  name="mage"
  code="MA"
  [[classes.histogram]]
    attribute="strength"
    weight=10.0
  [[classes.histogram]]
    attribute="dexterity"
    weight=15.0
  [[classes.histogram]]
    attribute="intelligence"
    weight=50.0
  [[classes.histogram]]
    attribute="constitution"
    weight=25.0
